### ISSUE TITLE
Add new 4.4 aggregation expressions

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1478]
- [x] Add $accumulator aggregation operator #1471
- [x] Add $binarySize aggregation operator #1472
- [x] Add $bsonSize aggregation operator #1473 
- [x] Add $function aggregation operator #1474 
- [x] Add $isNumber aggregation operator #1475
- [x] Add $replaceAll aggregation operator #1476
- [x] Add $replaceOne aggregation operator #1477
